package org.otika.honeybee.model;

// Generated Oct 4, 2013 5:46:07 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * Codetable generated by hbm2java
 */
@Entity
@Table(name = "codetable", catalog = "honeybee")
@XmlRootElement
public class Codetable implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 5682041335490710673L;
	private Long id;
	private String codetype;
	private String codevalue;
	private String codevaluefr;
	private String codevaluear;

	public Codetable() {
	}

	public Codetable(String codetype, String codevalue, String codevaluefr,
			String codevaluear) {
		this.codetype = codetype;
		this.codevalue = codevalue;
		this.codevaluefr = codevaluefr;
		this.codevaluear = codevaluear;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "codetype", nullable = false, length = 45)
	public String getCodetype() {
		return this.codetype;
	}

	public void setCodetype(String codetype) {
		this.codetype = codetype;
	}

	@Column(name = "codevalue", nullable = false, length = 45)
	public String getCodevalue() {
		return this.codevalue;
	}

	public void setCodevalue(String codevalue) {
		this.codevalue = codevalue;
	}

	@Column(name = "codevaluefr", nullable = false, length = 45)
	public String getCodevaluefr() {
		return this.codevaluefr;
	}

	public void setCodevaluefr(String codevaluefr) {
		this.codevaluefr = codevaluefr;
	}

	@Column(name = "codevaluear", nullable = false, length = 45)
	public String getCodevaluear() {
		return this.codevaluear;
	}

	public void setCodevaluear(String codevaluear) {
		this.codevaluear = codevaluear;
	}

}
