package org.otika.honeybee.model;

//Generated Sep 30, 2013 3:00:16 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;
import javax.xml.bind.annotation.XmlRootElement;

/**
* Comment generated by hbm2java
*/
@Entity
@Table(name = "comment", catalog = "honeybee")
@XmlRootElement
public class Comment implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 6244740124041501299L;
	private Long id;
	private Integer version;
	private Content content;
	private String cfname;
	private String comcontent;
	private Date datecreated = new Date();
	private Date dateupdated;
	private String email;
	private String url;

	public Comment() {
	}

	public Comment(Content content, String cfname, String content_1,
			Date datecreated) {
		this.content = content;
		this.cfname = cfname;
		this.comcontent = content_1;
		this.datecreated = datecreated;
	}

	public Comment(Content content, String cfname, String content_1,
			Date datecreated, Date dateupdated, String email, String url) {
		this.content = content;
		this.cfname = cfname;
		this.comcontent = content_1;
		this.datecreated = datecreated;
		this.dateupdated = dateupdated;
		this.email = email;
		this.url = url;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Version
	@Column(name = "version")
	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "content_id", nullable = false)
	public Content getContent() {
		return this.content;
	}

	public void setContent(Content content) {
		this.content = content;
	}

	@Column(name = "cfname", nullable = false, length = 45)
	public String getCfname() {
		return this.cfname;
	}

	public void setCfname(String cfname) {
		this.cfname = cfname;
	}

	@Column(name = "content", nullable = false, length = 65535)
	public String getComcontent() {
		return this.comcontent;
	}

	public void setComcontent(String comcontent) {
		this.comcontent = comcontent;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "datecreated", nullable = false, length = 19)
	public Date getDatecreated() {
		return this.datecreated;
	}

	public void setDatecreated(Date datecreated) {
		this.datecreated = datecreated;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dateupdated", length = 19)
	public Date getDateupdated() {
		return this.dateupdated;
	}

	public void setDateupdated(Date dateupdated) {
		this.dateupdated = dateupdated;
	}

	@Column(name = "email", length = 65)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "url", length = 95)
	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

}
