package org.otika.honeybee.model;

// Generated May 19, 2013 4:05:52 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Version;
import javax.xml.bind.annotation.XmlRootElement;

import org.hibernate.search.annotations.Field;

/**
 * Substance generated by hbm2java
 */
@Entity
@Table(name = "substance"
      , catalog = "honeybee")
@XmlRootElement
public class Substance implements java.io.Serializable
{

   /**
    * 
    */
   private static final long serialVersionUID = -104346266962448023L;
   private Long id;
   private Integer version;
   private String label;
   private String labelfr;
   private String labelar;
   private String description;
   private Set<Ingredient> ingredients = new HashSet<Ingredient>(0);

   public Substance()
   {
   }

   public Substance(String label, String labelfr, String labelar)
   {
      this.label = label;
      this.labelfr = labelfr;
      this.labelar = labelar;
   }

   public Substance(String label, String labelfr, String labelar, String description, Set<Ingredient> ingredients)
   {
      this.label = label;
      this.labelfr = labelfr;
      this.labelar = labelar;
      this.description = description;
      this.ingredients = ingredients;
   }

   @Id
   @GeneratedValue(strategy = IDENTITY)
   @Column(name = "id", unique = true, nullable = false)
   public Long getId()
   {
      return this.id;
   }

   public void setId(Long id)
   {
      this.id = id;
   }

   @Version
   @Column(name = "version")
   public Integer getVersion()
   {
      return this.version;
   }

   public void setVersion(Integer version)
   {
      this.version = version;
   }

   @Field
   @Column(name = "label", nullable = false, length = 45)
   public String getLabel()
   {
      return this.label;
   }

   public void setLabel(String label)
   {
      this.label = label;
   }

   @Column(name = "labelfr", nullable = false, length = 45)
   public String getLabelfr()
   {
      return this.labelfr;
   }

   public void setLabelfr(String labelfr)
   {
      this.labelfr = labelfr;
   }

   @Column(name = "labelar", nullable = false, length = 45)
   public String getLabelar()
   {
      return this.labelar;
   }

   public void setLabelar(String labelar)
   {
      this.labelar = labelar;
   }

   @Column(name = "description", length = 65535)
   public String getDescription()
   {
      return this.description;
   }

   public void setDescription(String description)
   {
      this.description = description;
   }

   @OneToMany(fetch = FetchType.LAZY, mappedBy = "substance")
   public Set<Ingredient> getIngredients()
   {
      return this.ingredients;
   }

   public void setIngredients(Set<Ingredient> ingredients)
   {
      this.ingredients = ingredients;
   }

   @Override
   public String toString()
   {
      return label + " "+labelar;
   }
}
