#!/bin/bash
# This is a simple build script and will be executed on your CI system if 
# available.  Otherwise it will execute while your application is stopped
# before the deploy step.  This script gets executed directly, so it
# could be python, php, ruby, etc.

echo " Setting UTF8 for MYSQLD";
pathtofile="/var/lib/openshift/51b8b47c4382ec3cf90002c3/mysql/conf/my.cnf"
sed -i '/mysqld]/ a\collation-server=utf8_general_ci' $pathtofile
sed -i '/mysqld]/ a\character-set-server=utf8' $pathtofile
exit 0;