#!/bin/bash
# This deploy hook gets executed after dependencies are resolved and the
# build hook has been run but before the application has been started back
# up again.  This script gets executed directly, so it could be python, php,
# ruby, etc.

#collation_server=utf8_unicode_ci
#character_set_server=utf8

echo "Must use a MySQL utility to set character set and collation to UTF8 or sed or tail or tee to append keys and values in ~/mysql/conf/my.cnf";
echo " under [mysqld] section";
echo " Setting UTF8 for MYSQLD";
pathtofile="/var/lib/openshift/51b8b47c4382ec3cf90002c3/mysql/conf/my.cnf"
sed -i '/mysqld]/ a\collation-server=utf8_general_ci' $pathtofile
sed -i '/mysqld]/ a\character-set-server=utf8' $pathtofile
exit 0;