#!/bin/bash
# This is a simple post deploy hook executed after your application 
# is deployed and started.  This script gets executed directly, so 
# it could be python, php, ruby, etc.

echo "Executing Post Deploy hook";
 
#/usr/bin/mysql -u adminQTnK1ed -pdY7YPB_VVzgR -e "SET character_set_database = utf8" honeybee > /dev/null
echo " Setting UTF8 for MYSQLD";
pathtofile="/var/lib/openshift/51b8b47c4382ec3cf90002c3/mysql/conf/my.cnf"
sed -i '/mysqld]/ a\collation-server=utf8_general_ci' $pathtofile
sed -i '/mysqld]/ a\character-set-server=utf8' $pathtofile
exit 0;
