#!/bin/bash
# This is a simple post deploy hook executed after your application 
# is deployed and started.  This script gets executed directly, so 
# it could be python, php, ruby, etc.

echo "Executing Post Deploy hook";
 
#/usr/bin/mysql -u adminQTnK1ed -pdY7YPB_VVzgR -e "SET character_set_database = utf8" honeybee > /dev/null
#collation_server=utf8_unicode_ci
#character_set_server=utf8

echo "Must use a MySQL utility to set character set and collation to UTF8 or sed or tail or tee to append keys and values in ~/mysql/conf/my.cnf";
echo " under [mysqld] section";
echo " Setting UTF8 for MYSQLD";
pathtofile="/var/lib/openshift/51b8b47c4382ec3cf90002c3/mysql/conf/my.cnf"
sed -i '/mysqld]/ a\collation-server=utf8_general_ci' $pathtofile
sed -i '/mysqld]/ a\character-set-server=utf8' $pathtofile

echo "Well as the mysql folder is protected, the sed command would probably fail"
/usr/bin/mysql -h $OPENSHIFT_MYSQL_DB_HOST -u $OPENSHIFT_MYSQL_DB_USERNAME --password=$OPENSHIFT_MYSQL_DB_PASSWORD -P $OPENSHIFT_MYSQL_DB_PORT -e 'SET GLOBAL character_set_server=utf8, collation_server=utf8_general_ci;'
exit 0;
