#!/bin/bash
# This is a simple script and will be executed on your CI system if 
# available.  Otherwise it will execute while your application is stopped
# before the build step.  This script gets executed directly, so it
# could be python, php, ruby, etc.

echo "Must use a MySQL utility to set character set and collation to UTF8 or sed or tail or tee to append keys and values in ~/mysql/conf/my.cnf";
echo " under [mysqld] section";
sed -i '/mysqld]/ a\collation-server=utf8_general_ci' ~/mysql/conf/my.cnf
sed -i '/mysqld]/ a\character-set-server=utf8' ~/mysql/conf/my.cnf
exit 0;