#!/bin/bash
# This is a simple script and will be executed on your CI system if 
# available.  Otherwise it will execute while your application is stopped
# before the build step.  This script gets executed directly, so it
# could be python, php, ruby, etc.

#collation_server=utf8_unicode_ci
#character_set_server=utf8

echo "Pre Build action hook is executing"

exit 0;