#!/bin/bash
# This is a simple script and will be executed on your CI system if 
# available.  Otherwise it will execute while your application is stopped
# before the build step.  This script gets executed directly, so it
# could be python, php, ruby, etc.

#collation_server=utf8_unicode_ci
#character_set_server=utf8

echo "Pre Build action hook is executing"
/usr/bin/mysql -h $OPENSHIFT_MYSQL_DB_HOST -u $OPENSHIFT_MYSQL_DB_USERNAME --password=$OPENSHIFT_MYSQL_DB_PASSWORD -P $OPENSHIFT_MYSQL_DB_PORT -e 'SET GLOBAL character_set_server=utf8, collation_server=utf8_general_ci, character_set_connection=utf8, character_set_database=utf8, character_set_client=utf8, character_set_results=utf8;'
exit 0;
exit 0;